const names = {
  structures: [
    'Bog',
    'Burrow',
    'Burrows',
    'Catacombs',
    'Cavern',
    'Caverns',
    'Cell',
    'Cemetary',
    'Chamber',
    'Cliff',
    'Cliffs',
    'Crypt',
    'Death',
    'Forest',
    'Graveyard',
    'Grotto',
    'Haunt',
    'Jungle',
    'Lair',
    'Marsh',
    'Mausoleum',
    'Maze',
    'Monolith',
    'Mountain',
    'Ossuary',
    'Pit',
    'Pits',
    'Quarters',
    'Swamp',
    'Tomb',
    'Tunnels',
    'Vault',
  ],
  adjectives: [
    'Abominable',
    'Ancient',
    'Ascendent',
    'Awoken',
    'Betrayed',
    'Bleak',
    'Broken',
    'Burning',
    'Conquered',
    'Cruel',
    'Crying',
    'Cursed',
    'Dank',
    'Dark',
    'Dead',
    'Deep',
    'Deluded',
    'Desolate',
    'Doomed',
    'Dreary',
    'Dying',
    'Eastern',
    'Empty',
    'Enigmatic',
    'Eternal',
    'Forgotten',
    'Forsaken',
    'Fractured',
    'Frozen',
    'Ghost',
    'Glistening',
    'Gloomy',
    'Haunted',
    'Howling',
    'Lost',
    'Lucent',
    'Mourning',
    'Northern',
    'Perished',
    'Renegade',
    'Restless',
    'Screaming',
    'Shadow',
    'Shrouded',
    'Silent',
    'Sleeping',
    'Slumbering',
    'Southern',
    'Sparkly',
    'Unknown',
    'Vanishing',
    'Voiceless',
    'Wailing',
    'Wandering',
    'Western',
    'Wild',
    'Yawning',
  ],
  subjects: [
    'Army',
    'Bear',
    'Cult',
    'Death',
    'Doctor',
    'Dragon',
    'Eagle',
    'Elf',
    'Emperor',
    'Empress',
    'Ghost',
    'Giant',
    'Goblin',
    'Guardian',
    'Jaguar',
    'King',
    'Lion',
    'Martyr',
    'Monk',
    'Ogre',
    'Oracle',
    'Paladin',
    'Priest',
    'Prince',
    'Princess',
    'Queen',
    'Rabbit',
    'Scorpion',
    'Snake',
    'Sorcerer',
    'Sorceress',
    'Spider',
    'Spirit',
    'Storm',
    'Warlock',
    'Widow',
    'Witch',
    'Wizard',
    'Wolf',
    'Wraith',
  ],
}

export default ({ app }, inject) => {
  const generateDungeonName = () => {
    const structure = names.structures[Math.floor(Math.random()*names.structures.length)],
          adjective = names.adjectives[Math.floor(Math.random()*names.adjectives.length)],
          subject = names.subjects[Math.floor(Math.random()*names.subjects.length)]

    const text = `${structure} of the ${adjective} ${subject}`

    return {
      text,
      parts: { structure, adjective, subject },
      id: text.toLowerCase().split(' ').join('-')
    }
  }

  inject('generateDungeonName', generateDungeonName)
}